# Generated by Django 6.0.7 on 2026-07-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pesapal_tracking_id_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
