# Generated by Django 6.0.7 on 2026-07-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_merchant_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('KES', 'KES'), ('USD', 'USD'), ('GBP', 'GBP')], default='KES', max_length=3),
        ),
    ]
