# Generated by Django 6.0.7 on 2026-07-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
