# Generated by Django 6.0.7 on 2026-07-20 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_orderitem_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('PESAPAL', 'Pesapal')], default='PESAPAL', max_length=20)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initialized', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('KES', 'KES'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3)),
                ('redirect_url', models.URLField(blank=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('provider_tracking_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('checkout_request', models.JSONField(blank=True, default=dict)),
                ('checkout_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
