# Generated by Django 6.0.7 on 2026-07-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('PESAPAL', 'Pesapal'), ('NOWPAYMENTS', 'NOWPayments'), ('PAYPAL', 'PayPal')], default='PESAPAL', max_length=20),
        ),
    ]
